version: "3.8"

services:
  frontend: 
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://backend:3001

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://db:27017

  db:
    image: mongo:6.0.2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
  
