apiVersion: apps/v1
kind: Deployment
metadata:
  name: backbone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: sadka/backend:v1.0
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "100m"