apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontbone
  namespace: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: sadka/frontend:v1.0
        ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_API_URL
            value: http://backend:3001/api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "100m"